<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <Version>1.0.8</Version>
    <Authors>z_compression contributors</Authors>
    <Product>z_compression</Product>
  </PropertyGroup>
</Project>
